#!/bin/bash

##
## This file is being executed by worm during startup
## Place it in your .config folder at ~/.config/worm/
##

## Autostart applications
# Start polybar
polybar mybar &

# Start terminal
alacritty &

## worm settings
# Set border width to 1 px
wormc border-width 1

# Set border color (base 10 value). F.e.: 0x1793D1 -> 1545169
wormc border-pixel 1545169
